### ISSUE TITLE
VideoKit freezes Unity Editor when recording audio

### ISSUE THREAD

**Issue by gillworks** [videokit-ai/videokit#128]
I'm on version 0.0.18, and when I'm recording audio with the video it will randomly freeze up the Unity Editor. It doesn't crash but I have to force quit it. If I turn off audio then this doesn't happen. My audio source is the audio listener on the main camera.

**Comment by olokobayusuf** [comment]
This should now be fixed in [VideoKit 0.0.22](https://github.com/videokit-ai/videokit/releases/tag/0.0.22). If you reproduce, please open a new issue.
