### ISSUE TITLE
Unity app crashes after calling StopRecording()

### ISSUE THREAD

**Issue by vitalii-vorobiov** [videokit-ai/videokit#131]
Sometimes when you call StopRecording() on VideoKitRecorder the app can crash with an error Thread 2: EXC_BAD_ACCESS (code=1, address=0x12e204010). This bug is only reproducible on iPhone 11 Pro (while on iPhone 14 Pro Max, everything is perfect).

The VideoKit version I was using is 0.0.19

I'm attaching the logs from a TestFlight user.
<img width="844" alt="Screenshot_2024-07-01_at_15 42 31" src="https://github.com/natmlx/videokit/assets/31632618/7b9f66ee-40d0-4262-8019-0977dcbe6940">

**Comment by olokobayusuf** [comment]
Fix coming in 0.0.20.

**Comment by olokobayusuf** [comment]
Fixed in 0.0.20.
