### ISSUE TITLE
Unity Freezes when Camera starts running on Awake

### ISSUE THREAD

**Issue by jkorn2324** [videokit-ai/videokit#134]
Unity freezes forever (no crash) whenever someone first starts running the game and the VideoKitCameraManager is set to Play On Awake. Here is additional info:

- Device: Mac M1 Silicon (2020)
- Unity Version: Unity 2022.3.20f1
- VideoKit Version: VideoKit 0.0.19

**Comment by olokobayusuf** [comment]
@jkorn2324 can you share the Editor logs?

**Comment by jkorn2324** [comment]
Here is the editor log file from the last time I was able to reproduce it:

[Editor.log](https://github.com/user-attachments/files/16203807/Editor.log)

**Comment by olokobayusuf** [comment]
@jkorn2324 can you reproduce this in an empty project? Your logs indicate that you've got a number of other packages in your project. We'd need to isolate this issue to VideoKit itself.

**Comment by jkorn2324** [comment]
I wasn't able to reproduce the issue in an empty project, but was able to still reproduce it in my other project. I did some debugging and what I found was the human texture capabilities functionality caused issues in my project. Whenever I turned the Human Texture Capabilities off, it would freeze Unity completely, but when I turned Human Texture Capabilities on, it would work completely fine.

For some reason, it would still trigger this line even if there were no Capabilities marked in the Unity Editor:
<img width="733" alt="Screenshot 2024-07-24 at 9 15 37 PM" src="https://github.com/user-attachments/assets/bcd88f53-67a3-4c5e-b2cd-f4f905cb332d">

**Comment by olokobayusuf** [comment]
@jkorn2324 are you saying this issue doesn't happen once you properly set the `Capabilities` setting? So Unity freezes when the human texture capability is on, but not off?

**Comment by jkorn2324** [comment]
Yes - when the Capabilities setting is properly set, everything works fine. But when it isn't (for me the Capabilities setting was set to 2) that's when Unity freezes - when this would happen, the Capabilities would be marked in the Unity Editor as "Nothing" even though the value was 2.

**Comment by olokobayusuf** [comment]
@jkorn2324 I think you can zero out the value by resetting the camera manager component. Click the three dots in the right corner of the component and click `Reset`.
