### ISSUE TITLE
External (UVC) cameras not recognised in iPadOS

### ISSUE THREAD

**Issue by mikeylemmon** [videokit-ai/videokit#135]
iPadOS 17 added support for external cameras using the USB video device class (UVC) — for example on the 2nd-gen iPad Pro I am testing with (iPadOS 17.5.1), apps like FaceTime, Zoom, and Webkit-based browsers all support external cameras and other capture devices (e.g. HDMI capture cards) connected to the USB-C port. Those same devices, however, are not being listed by `CameraDevice.Discover()` and thus are currently unavailable for use with VideoKit.

**Comment by olokobayusuf** [comment]
Coming in 0.0.20.

**Comment by olokobayusuf** [comment]
Implemented in 0.0.20.

**Comment by tomashined** [comment]
> Implemented in 0.0.20.

Hello. Could you provide a guide on how to set up multiple cameras and capture multiple images in Unity?

**Comment by mikeylemmon** [comment]
I have updated to 0.0.21, but external devices are still not being listed in the output of `CameraDevice.Discover()` — is there something else I need to do to enable the external cameras to be recognised?

**Comment by olokobayusuf** [comment]
> Hello. Could you provide a guide on how to set up multiple cameras and capture multiple images in Unity?

I'm not sure if this is what you're asking, but simultaneously streaming from multiple cameras is not yet supported. We can add it as a feature on iOS (we've implemented this in the past). Open an issue for a feature request.

**Comment by olokobayusuf** [comment]
> I have updated to 0.0.21, but external devices are still not being listed in the output of CameraDevice.Discover() — is there something else I need to do to enable the external cameras to be recognised?

@mikeylemmon I'm not sure what the issue could be. We followed [Apple's docs](https://developer.apple.com/documentation/avfoundation/avcapturedevicetypeexternal) to implement this feature. Just to confirm: you're testing on iPadOS 17?

**Comment by tomashined** [comment]
> > Hello. Could you provide a guide on how to set up multiple cameras and capture multiple images in Unity?
> 
> I'm not sure if this is what you're asking, but simultaneously streaming from multiple cameras is not yet supported. We can add it as a feature on iOS (we've implemented this in the past). Open an issue for a feature request.

I thought that this request was specifically about being able to get an image from multiple cameras, as iPadOS has introduced a feature that allows connecting other devices to it and viewing video from multiple cameras.

**Comment by olokobayusuf** [comment]
> I thought that this request was specifically about being able to get an image from multiple cameras, as iPadOS has introduced a feature that allows connecting other devices to it and viewing video from multiple cameras.

This issue was about adding support for discovering and streaming from UVC cameras. For streaming from multiple cameras (e.g. front and back) simultaneously, that's a separate feature.

**Comment by tomashined** [comment]
> > I thought that this request was specifically about being able to get an image from multiple cameras, as iPadOS has introduced a feature that allows connecting other devices to it and viewing video from multiple cameras.
> 
> This issue was about adding support for discovering and streaming from UVC cameras. For streaming from multiple cameras (e.g. front and back) simultaneously, that's a separate feature.

https://github.com/videokit-ai/videokit/issues/140
