### ISSUE TITLE
Billing plane issue on the archived Nat-corder

### ISSUE THREAD

**Issue by BasilDavid** [videokit-ai/videokit#138]
**Issue Description:**

We are encountering crashes in both Unity Editor and our iOS app when attempting to record video using Nat-corder. This issue started occurring recently without any changes to the video capture functionality in our codebase.

**Error Output:**

`NatCorder: MP4Recorder prepared video encoder at resolution 480x220@30.000000Hz with average bitrate 10000000 and keyframe interval 2s
NatML billing plan only allows for limited functionality. Check your plan and upgrade at https://hub.natml.ai/
NatML.Recorders.MP4Recorder:Create(Int32, Int32, Single, Int32, Int32, Int32, Int32, Int32)
NatML.Recorders.MP4Recorder:.ctor(Int32, Int32, Single, Int32, Int32, Int32, Int32, Int32)
** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NCFreeRecorder commitSamples:sampleCount:timestamp:]: unrecognized selector sent to instance 0x300505a40'
*** First throw call stack:
(0x19fd8cf20 0x197c12018 0x19fe96480 0x19fd29d60 0x19fd298d0 0x10aa2c270 0x10a434ed4 0x10b4580ac 0x10ca59fc4 0x10c1797b4 0x10c184a4c 0x10c25a624 0x10c974e70 0x10c974a5c 0x10c974a5c 0x10c974a5c 0x10c974a5c 0x10c974a5c 0x10c974a5c 0x10c984aa8 0x10c9925d8 0x10c99409c 0x10c9ad5e8 0x1fcbe506c 0x1fcbe00d8)
Uncaught exception: NSInvalidArgumentException: -[NCFreeRecorder commitSamples:sampleCount:timestamp:]: unrecognized selector sent to instance 0x300505a40
libc++abi: terminating due to uncaught exception of type NSException`

**Steps to Reproduce:**

1. Start the application.
2. Trigger the record functionality that uses Nat-corder.
3. Observe Unity Editor crash or iOS app freeze and crash.

**Additional Context:**

- The issue occurs regardless of recent changes to the codebase related to video recording.
- Subscription status for NatML (Nat-corder’s dependency) has been verified and is active.
- Attempting to catch the exception programmatically has not been successful, possibly due to the issue originating from the native side.

**Proposed Solution:**

Currently seeking advice or solutions on how to prevent the app from crashing when this exception occurs, or insights into potential causes from the Nat-corder or NatML community.

**Comment by olokobayusuf** [comment]
@BasilDavid we've migrated VideoKit over to its own service at [videokit.ai](https://videokit.ai). You can [login](https://www.videokit.ai/login) with the same email as NatML then check your billing plan. Also, make sure to upgrade to VideoKit. We have discontinued NatCorder.
