### ISSUE TITLE
NatML watermarks are present in our in-app recordings despite our payments being up to date

### ISSUE THREAD

**Issue by antholuisi** [videokit-ai/videokit#139]
- Unity 2022.2.27f1
- Natcorder 1.9.3
- Devices: all iOS, all Android (and Unity Editor)

Although we are using NatCorder, we are paying for a VideoKit license because it was the only way for us to remove the watermarks in our in-app recordings. However, last Friday, we noticed that the NatML watermark has reappeared in our in-app recordings. We checked our bank statements and confirmed that the payment was made as usual, so there doesn't seem to be a billing issue.

Thank you for your help in fixing this issue.

**Comment by olokobayusuf** [comment]
@antholuisi the quickest fix is to upgrade to VideoKit and generate a new access key to use. [See the docs](https://www.videokit.ai/recorders) for how to migrate.

**Comment by olokobayusuf** [comment]
This issue has been fixed in NatCorder. That said, I strongly recommend upgrading to VideoKit.
