### ISSUE TITLE
Synchronous capture and output of video from multiple cameras connected to an iPad with multi-stream support

### ISSUE THREAD

**Issue by tomashined** [videokit-ai/videokit#140]
> Hello. Could you provide a guide on how to set up multiple cameras and capture multiple images in Unity?

I'm not sure if this is what you're asking, but simultaneously streaming from multiple cameras is not yet supported. We can add it as a feature on iOS (we've implemented this in the past). Open an issue for a feature request.

_Originally posted by @olokobayusuf in https://github.com/videokit-ai/videokit/issues/135#issuecomment-2275778814_

**Comment by tomashined** [comment]
> > I thought that this request was specifically about being able to get an image from multiple cameras, as iPadOS has introduced a feature that allows connecting other devices to it and viewing video from multiple cameras.
> 
> This issue was about adding support for discovering and streaming from UVC cameras. For streaming from multiple cameras (e.g. front and back) simultaneously, that's a separate feature.

**Comment by olokobayusuf** [comment]
In the works: 6c2e2fe651b590e2f6630b614b80bde2d96e01a6

**Comment by olokobayusuf** [comment]
#162
