### ISSUE TITLE
Videos and screen captures do not get watermarked

### ISSUE THREAD

**Issue by alexandrefresnais** [videokit-ai/videokit#149]
Hi,

It seems that the watermarking feature is no longer working. Videos captured with the default recorder or images captured with `CaptureScreenshot` do not get watermarked.

This has been tested on an empty project on Unity 2022.3.21f1, running on both macOS 14.5 and iOS 17.6.1 (in both editor and player modes). VideoKit version is 0.0.21.

Here is my recorder setup with a random image taken from internet:

![Capture d’écran 2024-10-08 à 10 34 27](https://github.com/user-attachments/assets/eb5f6eaf-a52c-4925-8985-d927aff40363)

**Comment by olokobayusuf** [comment]
Hey @alexandrefresnais this will be fixed in the next update going out by Friday.

**Comment by alexandrefresnais** [comment]
Hi there,

Any update about this ?

**Comment by olokobayusuf** [comment]
@Muzazz @alexandrefresnais yes, the next update will be coming on Tuesday, and it will fix this issue.

**Comment by yuchenz27** [comment]
I got the same issue on Android using Unity 6000.0.27f1, is there a fix?

**Comment by olokobayusuf** [comment]
This has been fixed in the upcoming 0.0.23 release. I'll publish an alpha build tomorrow.

**Comment by olokobayusuf** [comment]
This has been fixed in VideoKit [`0.0.23-alpha.1`](https://www.npmjs.com/package/ai.videokit.videokit) (alpha build, not production-ready). A full production build is coming in 2-3 days.
