### ISSUE TITLE
VideoKit Android corrupt video

### ISSUE THREAD

**Issue by Apidcloud** [videokit-ai/videokit#153]
I wrote the same issue on discord channel (https://discord.com/channels/1268271520321376316/1303752149297270925), but I guess here it's better in case other people search for it on the web.

VideoKit 0.0.21 + ai fnx 0.0.26

Last year around this time (29th of November 2023) I asked the same question, but I can't find the older discord channel (did all the messages get deleted?). Basically we were using natcorder but found out the android recordings are corrupted (as described in https://discussions.unity.com/t/natcorder-video-recording-api/683160). At the time (~ 1 year ago), you sent me a test apk with the sharing option which seemed to solve this issue (using video kit 0.0.15 or 0.0.16 I believe). But today we are trying videokit (0.0.21) + ai fnx (0.0.26) (do we even need ai fnx if we only use video kit?), and I think the same issue is there (i.e., the video cannot be played on chrome). If I do a ffprobe on the recording I can see the following error:
```
Input buffer exhausted before END element found
[aist#0:0/aac @ 0x7fa739f1e780] [dec:aac @ 0x7fa739f0c740] Error submitting packet to decoder: Invalid data found when processing input
```

Are we missing something? We are using the free plan to test it out, as we want to make sure the issue is gone, but setting audio mode to None or changing the format doesn't seem to do anything. The video always comes as mp4 and with audio. We actually want the audio, but wanted to try out if removing it solves the issue as it did with natcorder.

The issue at the time was this, as far as I can remember (from the unity thread): 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/7b968afc-7b18-4717-93cc-ca1949cc3333">

**Edit**: 
found a screenshot with your reply from last year:
<img width="364" alt="image" src="https://github.com/user-attachments/assets/833c0707-4245-4baa-907b-e86b036bf54d">

**Comment by olokobayusuf** [comment]
@Apidcloud can you share an example video that doesn't play back in Chrome?

**Comment by Apidcloud** [comment]
Yeah, this one (zipped to avoid some compression from uploading to github)
[android-failed.mp4.zip](https://github.com/user-attachments/files/17653013/android-failed.mp4.zip)

**Comment by t3h32eKK** [comment]
Do you have any update on this? 

I have a similar problem, the recordings aren't playing in Chrome.

**Comment by olokobayusuf** [comment]
Hey @Apidcloud can you confirm that you are in fact using VideoKit? This issue has been fixed for quite some time, and an easy way to check this is to see that the MP4 tracks are always ordered such that the video track comes before audio:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'recording_2024_12_30_07_50_52_744.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-12-30T12:50:59.000000Z
    com.android.version: 14
  Duration: 00:00:06.20, start: 0.000000, bitrate: 2608 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m), 1280x2844, 2561 kb/s, 30.07 fps, 29.97 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2024-12-30T12:50:59.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 24000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 2024-12-30T12:50:59.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
```
Your video file is certainly broken (you can tell that this was pre-fix, because audio track is first), but that's gotta be an older version of our software. VideoKit does not have this issue. Try to reproduce this with VideoKit 0.0.22 and if you can do so, send me the video files along with the full app logs from `logcat`. Open a new issue.

**Comment by Apidcloud** [comment]
I can confirm that somehow our project was still using the wrong version and thus the issue. Tried with 0.0.22 and the videos are ok and play on Chrome!
