### ISSUE TITLE
show error when I use VideoKitRecorder component

### ISSUE THREAD

**Issue by IronYasuo** [videokit-ai/videokit#158]
![image](https://github.com/user-attachments/assets/00ac63a8-b8ce-4826-a2e2-7e870c6ed935)
![image](https://github.com/user-attachments/assets/8f00ed89-f4f9-4d2d-8a17-933368e47b26)

PC and android show same error:

InvalidOperationException: VideoKit plan does not support this operation. Check your plan and upgrade at https://videokit.ai
VideoKit.Internal.VideoKit.Throw (VideoKit.Internal.VideoKit+Status status) (at ./Library/PackageCache/ai.videokit.videokit@0.0.22/Runtime/Internal/VideoKit.cs:811)
VideoKit.MediaRecorder.Create (VideoKit.MediaRecorder+Format format, System.Int32 width, System.Int32 height, System.Single frameRate, System.Int32 sampleRate, System.Int32 channelCount, System.Int32 videoBitRate, System.Int32 keyframeInterval, System.Single compressionQuality, System.Int32 audioBitRate, System.String prefix) (at ./Library/PackageCache/ai.videokit.videokit@0.0.22/Runtime/MediaRecorder.cs:180)
VideoKit.VideoKitRecorder.StartRecordingAsync () (at ./Library/PackageCache/ai.videokit.videokit@0.0.22/Runtime/Components/VideoKitRecorder.cs:478)
VideoKit.VideoKitRecorder.StartRecording () (at ./Library/PackageCache/ai.videokit.videokit@0.0.22/Runtime/Components/VideoKitRecorder.cs:430)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <f7237cf7abef49bfbb552d7eb076e422>:0)

**Comment by olokobayusuf** [comment]
@IronYasuo are you on the free plan? If so, you need to be on the paid plan to record videos with VideoKit.
