### ISSUE TITLE
Crash after recording complete in Android app made with VideoKit v0.0.22 on Unity 6

### ISSUE THREAD

**Issue by thesanketkale** [videokit-ai/videokit#160]
Hi @olokobayusuf,

Our Android app is seeing a random crash after recording a video a second or third time while in an AR scene. Also, while recording a video the first time there seems to be some frame drops, but it gets through and completes processing, but after recording the second or third time in the same session, the app crashes.

Here are the Logs: 
[CrashLogs.txt](https://github.com/user-attachments/files/18250776/CrashLogs.txt)
[ErrorLogs.txt](https://github.com/user-attachments/files/18250777/ErrorLogs.txt)

Unity version: 6000.0.32f1
OS: Windows 11
Target build platform: Android
VideoKit version: 0.0.22

**Comment by olokobayusuf** [comment]
Hey @thesanketkale this doesn't look like a VideoKit crash. If it was from VideoKit, the stack trace would include `libVideoKit.so` but it doesn't. Also, the error logs show that the crash occurs right after AVPro tries to playback the video. VideoKit successfully finishes recording and invokes the recording callback:
```
I  [AVProVideo] Opening /storage/emulated/0/Android/data/com.UnityXR/files/my_saved_videos/638708131417866770/default.mp4 (offset 0) with API ExoPlayer
	UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
	RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
	UnityXR.MainMenu.Videos.Player.AVProVideoPlayer:LoadVideoPlayer(String, MediaPlayer, Boolean, Double)
	UnityXR.GamePlay.ScreenRecordingManager:OnRecordingCompleted(MediaAsset)
	UnityEngine.Events.UnityEvent`1:Invoke(T0)
	VideoKit.<StopRecordingAsync>d__43:MoveNext()
	System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
	System.Runtime.CompilerServices.MoveNextRunner:Run()
	UnityEngine.WorkRequest:Invoke()
	UnityEngine.UnitySynchronizationContext:Exec()
```
