### ISSUE TITLE
Access Key Works in editor but not in IOS build

### ISSUE THREAD

**Issue by Benjamin-Rhodes-Kropf** [videokit-ai/videokit#34]
Everything works great in the editor, including video and photo recording. BUT when I build a mobile IOS device I get the following errors:
"InvalidOperationExeption: NatCorder session token invalid. Check your NatML access key and plan"
"InvalidOperationExeption:  NatDevice session token invalid. Check your NatML access key and plan"
"InvalidOperationExeption:  NatDevice session token invalid. Check your NatML access key and plan"

I've been trouble shooting this bug for two days now any idea is welcome!

**Comment by olokobayusuf** [comment]
Hey there @Benjamin-Rhodes-Kropf , we're working on revamping this system. In the mean time, can you share the full logs from Xcode in a `.txt` attachment? There should be a preceding error that mentions why the session token is invalid.

**Comment by Aditya-Solulab** [comment]
Hey,
Same issue I found
"InvalidOperationExeption: NatCorder session token invalid. Check your NatML access key and plan"
"InvalidOperationExeption: NatDevice session token invalid. Check your NatML access key and plan"
"InvalidOperationExeption: NatDevice session token invalid. Check your NatML access key and plan"

I review the Xcode
there is missing ai.natml-natml framework

**Comment by Aditya-Solulab** [comment]
https://docs.google.com/document/d/1BfK6rbig598Xohham3xjaNsMoOhhrl7et-02k58OTMo/edit

This is the log kindly review

**Comment by Benjamin-Rhodes-Kropf** [comment]
Hey! Thanks for the reply; I rebuilt my code and changed my Unity version,
which seemed to work. However, I am now having problems with accessing the
camera and audio (it takes 3-4 seconds every time). Is that normal?

**Comment by olokobayusuf** [comment]
Hey @Aditya-Solulab , thanks for sharing your logs. Are you embedding your Unity app in another iOS app? I'll also follow up over email because I'll need potentially sensitive information to proceed on this.

**Comment by olokobayusuf** [comment]
> I rebuilt my code and changed my Unity version,
which seemed to work. However, I am now having problems with accessing the
camera and audio (it takes 3-4 seconds every time). Is that normal?

@Benjamin-Rhodes-Kropf this doesn't sound normal. I recommend opening a new issue with more info. Also by "it takes 3-4 seconds", do you mean it takes that long to start the camera? And what OS/device does this happen on?

**Comment by Benjamin-Rhodes-Kropf** [comment]
This is on iOS. Yes I mean it takes this long to start the camera. I will
submit a problem.

**Comment by Aditya-Solulab** [comment]
Hi yusuf,

No currently I am not embedding the Unity app into another app. I am using
unity 2021.3.4f1 its give me

 am using NATML Video kit
Everything works great in the editor, including video and photo recording.
BUT when I build a mobile IOS device I get the following errors:

"InvalidOperationExeption: NatCorder session token invalid. Check your
NatML access key and plan"
"InvalidOperationExeption: NatDevice session token invalid. Check your
NatML access key and plan"
"InvalidOperationExeption: NatDevice session token invalid. Check your
NatML access key and plan"

I've been having trouble shooting this bug for two days now any idea is
welcome!

I am review the Issue on git there also no answer
https://github.com/natmlx/videokit/issues/34

I am attaching the logs
kindly review the logs
https://docs.google.com/document/d/1BfK6rbig598Xohham3xjaNsMoOhhrl7et-02k58OTMo/edit

Any help is really appreciated.

Thanks in advance

**Comment by olokobayusuf** [comment]
Hey @Aditya-Solulab , can you try the [0.0.14-alpha.1](https://www.npmjs.com/package/ai.natml.videokit) pre-release build? We've reimplemented how access keys are implemented, so this issue should no longer happen.

**Comment by Aditya-Solulab** [comment]
HI Natmlx/Videokit,
I tried new  0.0.14-alpha.1
<https://www.npmjs.com/package/ai.natml.videokit>  version.
but I got media assets is null in the editor on StopVideoRecording

Thanks

**Comment by Aditya-Solulab** [comment]
Hi
I tried new version   0.0.14-alpha.1
<https://www.npmjs.com/package/ai.natml.videokit>  version.
In editor works the session key(access key)
but in IOS Device
valid. Check your NatML access key.
  at VideoKit.Internal.VideoKit.CheckStatus
(VideoKit.Internal.VideoKit+Status status) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.PrepareEncoder () [0x00000] in
<00000000000000000000000000000000>:0
  at
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine]
(TStateMachine& stateMachine) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.PrepareEncoder () [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.Awake () [0x00000] in
<00000000000000000000000000000000>:0
  at
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine]
(TStateMachine& stateMachine) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.Awake () [0x00000] in
<00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---

  at VideoKit.VideoKitRecorder.Awake () [0x00000] in
<00000000000000000000000000000000>:0
  at
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine]
(TStateMachine& stateMachine) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.Awake () [0x00000] in
<00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---

  at
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0
(System.Object state) [0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke ()
[0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in
<00000000000000000000000000000000>:0

2023-07-04 17:28:06.399054+0530 xrnode[2486:925131] UnityARKit: Updating
ARSession configuration with <ARWorldTrackingConfiguration: 0x2839e1400
worldAlignment=Gravity lightEstimation=Enabled frameSemantics=None
videoFormat=<ARVideoFormat: 0x282624be0 imageResolution=(1920, 1440)
pixelFormat=(420f) framesPerSecond=(60)
captureDeviceType=AVCaptureDeviceTypeBuiltInWideAngleCamera
captureDevicePosition=(1)> autoFocus=Enabled environmentTexturing=None
wantsHDREnvironmentTextures=Enabled planeDetection=Horizontal
collaboration=Disabled userFaceTracking=Disabled sceneReconstruction=None
appClipCodeTracking=Disabled>
2023-07-04 17:28:06.410703+0530 xrnode[2486:925131] UnityARKit: Updating
ARSession configuration with <ARWorldTrackingConfiguration: 0x2839e3800
worldAlignment=Gravity lightEstimation=Enabled frameSemantics=None
videoFormat=<ARVideoFormat: 0x282624be0 imageResolution=(1920, 1440)
pixelFormat=(420f) framesPerSecond=(60)
captureDeviceType=AVCaptureDeviceTypeBuiltInWideAngleCamera
captureDevicePosition=(1)> autoFocus=Enabled environmentTexturing=None
wantsHDREnvironmentTextures=Enabled planeDetection=Horizontal
collaboration=Disabled userFaceTracking=Disabled sceneReconstruction=None
appClipCodeTracking=Disabled>
InvalidOperationException: VideoKit session token is invalid. Check your
NatML access key.
  at VideoKit.Internal.VideoKit.CheckStatus
(VideoKit.Internal.VideoKit+Status status) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.Recorders.MP4Recorder.Create (System.Int32 width,
System.Int32 height, System.Single frameRate, System.Int32 sampleRate,
System.Int32 channelCount, System.Int32 videoBitRate, System.Int32
keyframeInterval, System.Int32 audioBitRate) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.CreateRecorder (System.Int32 width,
System.Int32 height, System.Int32 sampleRate, System.Int32 channelCount)
[0x00000] in <00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.StartRecording () [0x00000] in
<00000000000000000000000000000000>:0
  at
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine]
(TStateMachine& stateMachine) [0x00000] in
<00000000000000000000000000000000>:0
  at VideoKit.VideoKitRecorder.StartRecording () [0x00000] in
<00000000000000000000000000000000>:0
  at XRStudio.Scipts.UI.UIController.OnVideoRecordButtonDown () [0x00000]
in <00000000000000000000000000000000>:0
  at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in
<00000000000000000000000000000000>:0
  at XRStudio.Scipts.UI.VideoRecordButton+<Countdown>d__18.MoveNext ()
[0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext
(System.Collections.IEnumerator enumerator, System.IntPtr
returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---

  at
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0
(System.Object state) [0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke ()
[0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00000] in
<00000000000000000000000000000000>:0

throw this error

**Comment by olokobayusuf** [comment]
Hey @Aditya-Solulab can you share the full logs from Xcode in a `.txt` attachment? The logs you shared are truncated.

**Comment by Aditya-Solulab** [comment]
Hey Natmlx/Videokit,
I reset up my Unity Its works now

**Comment by olokobayusuf** [comment]
@Aditya-Solulab sounds good. I'll keep this issue open until we publish the 0.0.14 update. In the mean time, let me know if you face any issues.

**Comment by Aditya-Solulab** [comment]
Thanks a lot for understanding.

**Comment by Aditya-Solulab** [comment]
HI
I reported a new issue.
https://github.com/natmlx/videokit/issues/41

Issue related to unity and IOS Integration

Thanks in advance

**Comment by olokobayusuf** [comment]
[Fixed in VideoKit 0.0.14](https://github.com/natmlx/videokit/releases/tag/0.0.14).
