### ISSUE TITLE
Camera image is frozen when restored from background (Android)

### ISSUE THREAD

**Issue by LoopIssuer** [videokit-ai/videokit#56]
Hi,
The camera image is frozen when restored from the background (Android).
It happens after about 1 minute, when app is in the background.
When I use off/on camera or change device (front/back), it works properly.

**Comment by olokobayusuf** [comment]
Hey @LoopIssuer , this is on the list to fix in the 0.0.15 update!

**Comment by olokobayusuf** [comment]
@LoopIssuer no ETA yet, but [there are alpha builds](https://www.npmjs.com/package/ai.natml.videokit) coming today and later this week.

**Comment by SebastianTusk** [comment]
This issue is still reproducible in version 0.0.17.

**Comment by olokobayusuf** [comment]
[Fixed in 0.0.22](https://github.com/videokit-ai/videokit/releases/tag/0.0.22).
