### ISSUE TITLE
VideoKit session token is invalid. Check your NatML access key.

### ISSUE THREAD

**Issue by LoopIssuer** [videokit-ai/videokit#64]
Hi
We have noticed some of the logs on the analytics with this message:

> VideoKit session token is invalid. Check your NatML access key.

Affected devices are so far:
OPPO/CPH2385/OP571DL1
Android OS 12 / API-31 (SP1A.210812.016/S.R4T2.d1c72a-3591e)
CPU ARM64

LGE/LM-G900TM/mcaymanlm
Android OS 12 / API-31 (SKQ1.211103.001/6885120230801)
CPU ARM64

Hard to say if this ends with some crash or sth like that. 
My question is - can this be an issue that blocks using Videokit, or maybe it is only warning or false error?

[VideoKitToken.txt](https://github.com/natmlx/videokit/files/13110959/VideoKitToken.txt)

**Comment by olokobayusuf** [comment]
Hey @LoopIssuer , this issue has been reported on Windows. On Android, can you share the full logs from `logcat`? Also, make sure that you're on VideoKit 0.0.15.

**Comment by olokobayusuf** [comment]
Hey @LoopIssuer , can you upgrade to VideoKit 0.0.15? The session token handling was improved in the final release.

**Comment by olokobayusuf** [comment]
Also, this should never result in a crash.

**Comment by olokobayusuf** [comment]
That's correct. It throws an `InvalidOperationException` in code that you can surround in `try { ... } catch`

**Comment by olokobayusuf** [comment]
Hey @LoopIssuer following up on this. If the token is invalid, then you will get an `InvalidOperationException` when you call `VideoKitRecorder.StartRecording`, `MediaRecorder.Create`, `CameraDevice.StartRunning`, or `AudioDevice.StartRunning`. You can catch these errors with a `try { } catch` block.
